version: '3.3'
services:
  pd0:
    image: ipd:latest
    ports:
      - "2379"
    volumes:
      - ./run/data:/data
      - ./run/logs:/logs
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --data-dir=/data/pd0
      - --log-file=/logs/pd0.log
    restart: on-failure
  tikv0:
    image: itikv:latest
    volumes:
      - ./run/data:/data
      - ./run/logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --data-dir=/data/tikv0
      - --pd=pd0:2379
      - --log-file=/logs/tikv0.log
    depends_on:
      - "pd0"
    restart: on-failure
  tikv1:
    image: itikv:latest
    volumes:
      - ./run/data:/data
      - ./run/logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv1:20160
      - --data-dir=/data/tikv1
      - --pd=pd0:2379
      - --log-file=/logs/tikv1.log
    depends_on:
      - "pd0"
    restart: on-failure
  tikv2:
    image: itikv:latest
    volumes:
      - ./run/data:/data
      - ./run/logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv2:20160
      - --data-dir=/data/tikv2
      - --pd=pd0:2379
      - --log-file=/logs/tikv2.log
    depends_on:
      - "pd0"
    restart: on-failure
  tidb0:
    image: itidb:latest
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./run/logs:/logs
    command:
      - --store=tikv
      - --path=pd0:2379
      - --log-file=/logs/tidb0.log
      - --advertise-address=tidb0
    depends_on:
      - "tikv0"
      - "tikv1"
      - "tikv2"
    restart: on-failure
